class MediaPackageV2Channel < ::ApplicationRecord
  extend _ActiveRecord_Relation_ClassMethods[MediaPackageV2Channel, ActiveRecord_Relation, String]

  module GeneratedAttributeMethods
    def id: () -> String

    def id=: (String) -> String

    def id?: () -> bool

    def id_changed?: () -> bool

    def id_change: () -> [ String?, String? ]

    def id_will_change!: () -> void

    def id_was: () -> String?

    def id_previously_changed?: () -> bool

    def id_previous_change: () -> Array[String?]?

    def id_previously_was: () -> String?

    def id_before_last_save: () -> String?

    def id_change_to_be_saved: () -> Array[String?]?

    def id_in_database: () -> String?

    def saved_change_to_id: () -> Array[String?]?

    def saved_change_to_id?: () -> bool

    def will_save_change_to_id?: () -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def streaming_id: () -> String

    def streaming_id=: (String) -> String

    def streaming_id?: () -> bool

    def streaming_id_changed?: () -> bool

    def streaming_id_change: () -> [ String?, String? ]

    def streaming_id_will_change!: () -> void

    def streaming_id_was: () -> String?

    def streaming_id_previously_changed?: () -> bool

    def streaming_id_previous_change: () -> Array[String?]?

    def streaming_id_previously_was: () -> String?

    def streaming_id_before_last_save: () -> String?

    def streaming_id_change_to_be_saved: () -> Array[String?]?

    def streaming_id_in_database: () -> String?

    def saved_change_to_streaming_id: () -> Array[String?]?

    def saved_change_to_streaming_id?: () -> bool

    def will_save_change_to_streaming_id?: () -> bool

    def restore_streaming_id!: () -> void

    def clear_streaming_id_change: () -> void

    def media_package_v2_channel_group_id: () -> String?

    def media_package_v2_channel_group_id=: (String?) -> String?

    def media_package_v2_channel_group_id?: () -> bool

    def media_package_v2_channel_group_id_changed?: () -> bool

    def media_package_v2_channel_group_id_change: () -> [ String?, String? ]

    def media_package_v2_channel_group_id_will_change!: () -> void

    def media_package_v2_channel_group_id_was: () -> String?

    def media_package_v2_channel_group_id_previously_changed?: () -> bool

    def media_package_v2_channel_group_id_previous_change: () -> Array[String?]?

    def media_package_v2_channel_group_id_previously_was: () -> String?

    def media_package_v2_channel_group_id_before_last_save: () -> String?

    def media_package_v2_channel_group_id_change_to_be_saved: () -> Array[String?]?

    def media_package_v2_channel_group_id_in_database: () -> String?

    def saved_change_to_media_package_v2_channel_group_id: () -> Array[String?]?

    def saved_change_to_media_package_v2_channel_group_id?: () -> bool

    def will_save_change_to_media_package_v2_channel_group_id?: () -> bool

    def restore_media_package_v2_channel_group_id!: () -> void

    def clear_media_package_v2_channel_group_id_change: () -> void

    def name: () -> String?

    def name=: (String?) -> String?

    def name?: () -> bool

    def name_changed?: () -> bool

    def name_change: () -> [ String?, String? ]

    def name_will_change!: () -> void

    def name_was: () -> String?

    def name_previously_changed?: () -> bool

    def name_previous_change: () -> Array[String?]?

    def name_previously_was: () -> String?

    def name_before_last_save: () -> String?

    def name_change_to_be_saved: () -> Array[String?]?

    def name_in_database: () -> String?

    def saved_change_to_name: () -> Array[String?]?

    def saved_change_to_name?: () -> bool

    def will_save_change_to_name?: () -> bool

    def restore_name!: () -> void

    def clear_name_change: () -> void
  end
  include GeneratedAttributeMethods

  def origin_endpoint: () -> MediaPackageV2OriginEndpoint?
  def origin_endpoint=: (MediaPackageV2OriginEndpoint?) -> MediaPackageV2OriginEndpoint?
  def build_origin_endpoint: (untyped) -> MediaPackageV2OriginEndpoint
  def create_origin_endpoint: (untyped) -> MediaPackageV2OriginEndpoint
  def create_origin_endpoint!: (untyped) -> MediaPackageV2OriginEndpoint
  def reload_origin_endpoint: () -> MediaPackageV2OriginEndpoint?
  def streaming: () -> Streaming
  def streaming=: (Streaming?) -> Streaming?
  def reload_streaming: () -> Streaming?
  def build_streaming: (untyped) -> Streaming
  def create_streaming: (untyped) -> Streaming
  def create_streaming!: (untyped) -> Streaming
  def channel_group: () -> MediaPackageV2ChannelGroup
  def channel_group=: (MediaPackageV2ChannelGroup?) -> MediaPackageV2ChannelGroup?
  def reload_channel_group: () -> MediaPackageV2ChannelGroup?
  def build_channel_group: (untyped) -> MediaPackageV2ChannelGroup
  def create_channel_group: (untyped) -> MediaPackageV2ChannelGroup
  def create_channel_group!: (untyped) -> MediaPackageV2ChannelGroup
  module GeneratedAssociationMethods
  end
  include GeneratedAssociationMethods

  module GeneratedRelationMethods
  end

  class ActiveRecord_Relation < ::ActiveRecord::Relation
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[MediaPackageV2Channel, String]
    include Enumerable[MediaPackageV2Channel]
  end

  class ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[MediaPackageV2Channel, String]
  end
end
