FROM public.ecr.aws/docker/library/ruby:4.0.1-slim
WORKDIR /app
RUN apt-get update \
    && apt-get -y install \
    build-essential \
    curl \
    default-libmysqlclient-dev \
    git \
    libmariadb3 \
    libvips42 \
    shared-mime-info \
    vim \
    wget
ENV RUBY_YJIT_ENABLE=1
