version: "3.8"
services:
  app:
    build: .
    environment:
      RAILS_ENV: development
    volumes:
    - .:/app
    ports:
    - "3000:3000"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dreamkast
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - mysql-data:/var/lib/mysql
    ports:
    - "3306:3306"
volumes:
  mysql-data:
