version: "3.8"
services:
  app:
    build: .
    entrypoint: /bin/sh -c "docker/wait-for-it.sh db:3306 --timeout=600 && bundle exec rails db:migrate && bundle exec rails db:seed_fu && ./entrypoint.sh"
    environment: &dkenv
      RAILS_ENV: production
      NODE_ENV: production
      SENTRY_DSN: ${SENTRY_DSN}
      S3_REGION: ap-northeast-1
      S3_BUCKET: ${S3_BUCKET}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ap-northeast-1
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: dreamkast
      REDIS_URL: redis://redis:6379
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      SQS_MAIL_QUEUE_URL: ${SQS_MAIL_QUEUE_URL}
    tty: true
    stdin_open: true
    tmpfs:
      - /app/tmp
    ports:
      - "3000:3000"
    depends_on:
      - db
  mail-worker:
    build: .
    entrypoint: /bin/sh -c "docker/wait-for-it.sh db:3306 --timeout=600 && bundle exec aws_sqs_active_job --queue mail"
    environment:
      <<: *dkenv
    tty: true
    stdin_open: true
    tmpfs:
      - /app/tmp
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dreamkast
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    cap_add:
      - SYS_NICE
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    volumes:
    - mysql-data:/var/lib/mysql
    ports:
    - "3306:3306"
  redis:
    image: "redis:6"
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
  nginx:
    image: nginx
    volumes:
    - ./config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 8080:80
  ui:
    image: 607167088920.dkr.ecr.ap-northeast-1.amazonaws.com/dreamkast-ui:main
    ports:
    - 3001:3001
volumes:
  mysql-data:
  redis-data:
