version: "3.8"
services:
  app: &app_base
    build: .
    command: /bin/sh -c "bundle install && yarn install --check-files && bundle exec rails s -b 0.0.0.0 --dev-caching"
    environment:
      RAILS_ENV: development
      NODE_ENV: development
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: dreamkast
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - bundle:/app/vendor/bundle
      - node-modules:/app/node_modules
      - packs:/app/public/packs
      - tmp:/app/tmp
    ports:
      - "3000:3000"
    depends_on:
      - db
  webpack:
    <<: *app_base
    entrypoint: /bin/sh -c "docker/wait-for-it.sh app:3000 --timeout=600 && bundle install && yarn install --check-files && bin/webpack-dev-server"
    environment:
      RAILS_ENV: development
      NODE_ENV: development
      BUNDLE_APP_CONFIG: ./.bundle
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - 3035:3035
    tty: true
    stdin_open: true
    depends_on:
      - app
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dreamkast
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - mysql-data:/var/lib/mysql
    ports:
    - "3306:3306"
volumes:
  mysql-data:
  bundle:
  node-modules:
  packs:
  tmp:
