version: "3.8"
services:
  app:
    build: .
    environment:
      RAILS_ENV: test
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    tty: true
    entrypoint:
      - /bin/sh
      - -c
      - |
        docker/wait-for-it.sh db:3306
        rails db:create dreamkast_test
        rails db:environment:set RAILS_ENV=test
        rspec
