apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dreamkast
    tier: dreamkast-mail-worker
  name: dreamkast-mail-worker
spec:
  selector:
    matchLabels:
      app: dreamkast
      tier: dreamkast-mail-worker
  template:
    metadata:
      labels:
        app: dreamkast
        tier: dreamkast-mail-worker
    spec:
      containers:
      - name: dreamkast
        image: 607167088920.dkr.ecr.ap-northeast-1.amazonaws.com/dreamkast-ecs:main
        imagePullPolicy: Always
        command: ["bundle"]
        args: [
          "exec",
          "aws_sqs_active_job",
          "--queue",
          "mail"
        ]
        env:
        - name: RAILS_ENV
          value: "production"
        - name: AWS_REGION
          value: "ap-northeast-1"
        - name: MYSQL_HOST
          value: "dreamkast-mysql"
        - name: REDIS_URL
          value: "redis://dreamkast-redis:6379"
        - name: SENTRY_DSN
          value: "https://443f0535beb64cd8b2e995d001e0903b@o414348.ingest.sentry.io/5350644"
        - name: S3_BUCKET
          value: "dreamkast-test-bucket"
        - name: S3_REGION
          value: ap-northeast-1
        - name: SQS_MAIL_QUEUE_URL
          value: "https://sqs.ap-northeast-1.amazonaws.com/607167088920/devMailQueue.fifo"
        - name: RAILS_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: rails-app-secret
              key: rails-app-secret
        - name: AUTH0_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: dreamkast-secret
              key: AUTH0_CLIENT_ID
        - name: AUTH0_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: dreamkast-secret
              key: AUTH0_CLIENT_SECRET
        - name: AUTH0_DOMAIN
          valueFrom:
            secretKeyRef:
              name: dreamkast-secret
              key: AUTH0_DOMAIN
        - name: REVIEW_APP
          valueFrom:
            secretKeyRef:
              name: dreamkast-secret
              key: REVIEW_APP
