apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: dreamkast-secret
spec:
  backendType: secretsManager
  data:
    - key: dreamkast/reviewapp-env
      name: AUTH0_CLIENT_ID
      property: AUTH0_CLIENT_ID
    - key: dreamkast/reviewapp-env
      name: AUTH0_CLIENT_SECRET
      property: AUTH0_CLIENT_SECRET
    - key: dreamkast/reviewapp-env
      name: AUTH0_DOMAIN
      property: AUTH0_DOMAIN
    - key: dreamkast/reviewapp-env
      name: REVIEW_APP
      property: REVIEW_APP
