apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dreamkast-dk-917
bases:
- ../../../base
resources:
- ns.yaml
- mysql.yaml
- redis.yaml
- externalsecret.yaml
- ingress.yaml
patchesStrategicMerge:
- deployment-dreamkast.yaml
- deployment-mail-worker.yaml
