class AdminProfile < ApplicationRecord
  include ActionView::Helpers::UrlHelper

  def has_avatar?: () -> untyped

  def avatar_or_dummy_url: () -> untyped

  def twitter_link: () -> untyped

  def github_link: () -> untyped
end
