class LiveStreamIvs < LiveStream
  include EnvHelper

  def name: () -> untyped

  def channel_arn: () -> string

  def playback_url: () -> untyped

  def ingest_endpoint: () -> untyped

  def stream_key: () -> untyped

  def get_stream: () -> untyped

  def viewer_count: () -> untyped

  def ingest_url: () -> ::String

  private

  def ivs_client: () -> untyped

  def recording_configuration_arn: () -> untyped
end
