class EmailValidator < ActiveModel::EachValidator
  def validate_each: (untyped record, untyped attribute, untyped value) -> untyped
end

class TelValidator < ActiveModel::EachValidator
  def validate_each: (untyped record, untyped attribute, untyped value) -> untyped
end

class Profile < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  def sub_and_email_must_be_unique_in_a_conference: () -> untyped

  def self.export: (untyped event_id) -> untyped
end
