class Talk < ApplicationRecord
  SLOT_MAP: ::Array[untyped]

  def self.import: (untyped file) -> untyped

  def self.export_csv: (untyped conference, untyped talks, ?::String track_name, ?::String date) -> untyped

  def self.updatable_attributes: () -> ::Array["id" | "conference_id" | "title" | "abstract" | "track_id" | "talk_category_id" | "talk_difficulty_id" | "conference_day_id" | "start_time" | "end_time" | "movie_url" | "show_on_timetable" | "video_published" | "document_url" | "additional_documents"]

  def track_name: () -> untyped

  def slot_number: () -> String

  def talk_number: () -> untyped

  def day_slot: () -> untyped

  def row_start: () -> untyped

  def row_end: () -> untyped

  def self.find_by_params: (untyped day_id, untyped slot_number_param, untyped track_id) -> untyped

  def speaker_names: () -> untyped

  def speaker_company_names: () -> untyped

  def speaker_twitter_ids: () -> untyped

  def difficulty: () -> untyped

  def category: () -> untyped

  def duration: () -> untyped

  def on_air?: () -> untyped

  def video_platform: () -> untyped

  def video_id: () -> untyped

  def time: () -> (40 | untyped)

  def start_to_end: () -> untyped

  def expected_participant_params: () -> untyped

  def execution_phase_params: () -> untyped

  def archived?: () -> untyped

  def sponsor_session?: () -> untyped

  def create_or_update_proposal_item: (untyped label, untyped params) -> untyped

  def proposal_item_value: (untyped label) -> (nil | untyped)

  private

  def validate_expected_participants: () -> untyped

  def validate_execution_phases: () -> untyped
end
