apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    dreamkast.cloudnativedays.jp/app-commit-hash: c767345c639be2f02d3bff527138e7ecf9c6c291
    dreamkast.cloudnativedays.jp/app-organization: cloudnativedaysjp
    dreamkast.cloudnativedays.jp/app-repository: dreamkast
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: dreamkast-development-dk-895
  namespace: argocd
spec:
  destination:
    namespace: dreamkast-dk-895
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/app/dreamkast/overlays/development/dk-895
    repoURL: https://github.com/cloudnativedaysjp/dreamkast-infra
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
