interface _RbsRailsPathHelpers
  def rails_mailers_path: (*untyped) -> String
  def rails_info_properties_path: (*untyped) -> String
  def rails_info_routes_path: (*untyped) -> String
  def rails_info_path: (*untyped) -> String
  def root_path: (*untyped) -> String
  def auth_auth0_callback_path: (*untyped) -> String
  def auth_failure_path: (*untyped) -> String
  def logout_path: (*untyped) -> String
  def api_v1_path: (*untyped) -> String
  def api_v1_conference_path: (*untyped) -> String
  def api_v1_talks_path: (*untyped) -> String
  def api_v1_talk_path: (*untyped) -> String
  def api_v1_tracks_path: (*untyped) -> String
  def api_v1_track_path: (*untyped) -> String
  def api_v1_sponsors_path: (*untyped) -> String
  def api_v1_speakers_path: (*untyped) -> String
  def api_v1_speaker_path: (*untyped) -> String
  def api_v1_chat_messages_path: (*untyped) -> String
  def api_v1_chat_message_path: (*untyped) -> String
  def api_v1_booth_path: (*untyped) -> String
  def auth_auth0_path: (*untyped) -> String
  def admin_path: (*untyped) -> String
  def admin_debug_path: (*untyped) -> String
  def admin_chat_path: (*untyped) -> String
  def admin_accesslog_path: (*untyped) -> String
  def admin_users_path: (*untyped) -> String
  def admin_statistics_path: (*untyped) -> String
  def admin_export_statistics_path: (*untyped) -> String
  def admin_destroy_user_path: (*untyped) -> String
  def edit_admin_admin_profile_path: (*untyped) -> String
  def admin_admin_profile_path: (*untyped) -> String
  def admin_sponsors_path: (*untyped) -> String
  def edit_admin_sponsor_path: (*untyped) -> String
  def admin_sponsor_path: (*untyped) -> String
  def admin_booths_path: (*untyped) -> String
  def admin_booth_path: (*untyped) -> String
  def admin_conferences_path: (*untyped) -> String
  def edit_admin_conference_path: (*untyped) -> String
  def admin_conference_path: (*untyped) -> String
  def admin_speakers_path: (*untyped) -> String
  def edit_admin_speaker_path: (*untyped) -> String
  def admin_speaker_path: (*untyped) -> String
  def admin_export_speakers_path: (*untyped) -> String
  def admin_export_profiles_path: (*untyped) -> String
  def admin_talks_path: (*untyped) -> String
  def admin_proposals_path: (*untyped) -> String
  def admin_videos_path: (*untyped) -> String
  def admin_timetables_path: (*untyped) -> String
  def admin_timetable_path: (*untyped) -> String
  def admin_announcements_path: (*untyped) -> String
  def new_admin_announcement_path: (*untyped) -> String
  def edit_admin_announcement_path: (*untyped) -> String
  def admin_announcement_path: (*untyped) -> String
  def admin_speaker_announcements_path: (*untyped) -> String
  def new_admin_speaker_announcement_path: (*untyped) -> String
  def edit_admin_speaker_announcement_path: (*untyped) -> String
  def admin_speaker_announcement_path: (*untyped) -> String
  def admin_publish_timetable_path: (*untyped) -> String
  def admin_close_timetable_path: (*untyped) -> String
  def admin_preview_timetable_path: (*untyped) -> String
  def admin_start_on_air_path: (*untyped) -> String
  def admin_stop_on_air_path: (*untyped) -> String
  def admin_start_recording_path: (*untyped) -> String
  def admin_stop_recording_path: (*untyped) -> String
  def admin_tracks_path: (*untyped) -> String
  def admin_update_offset_path: (*untyped) -> String
  def admin_attachment_path: (*untyped) -> String
  def admin_team_path: (*untyped) -> String
  def admin_live_stream_ivs_path: (*untyped) -> String
  def admin_bulk_create_ivs_path: (*untyped) -> String
  def admin_bulk_delete_ivs_path: (*untyped) -> String
  def admin_bulk_create_media_live_path: (*untyped) -> String
  def admin_bulk_delete_media_live_path: (*untyped) -> String
  def admin_bulk_create_media_package_path: (*untyped) -> String
  def admin_bulk_delete_media_package_path: (*untyped) -> String
  def admin_harvest_jobs_path: (*untyped) -> String
  def new_admin_harvest_job_path: (*untyped) -> String
  def edit_admin_harvest_job_path: (*untyped) -> String
  def admin_harvest_job_path: (*untyped) -> String
  def team_path: (*untyped) -> String
  def speakers_entry_path: (*untyped) -> String
  def speakers_guidance_path: (*untyped) -> String
  def speakers_path: (*untyped) -> String
  def speaker_path: (*untyped) -> String
  def speaker_dashboard_path: (*untyped) -> String
  def speaker_dashboard_speakers_path: (*untyped) -> String
  def new_speaker_dashboard_speaker_path: (*untyped) -> String
  def edit_speaker_dashboard_speaker_path: (*untyped) -> String
  def speaker_dashboard_speaker_path: (*untyped) -> String
  def speaker_dashboard_video_registrations_path: (*untyped) -> String
  def new_speaker_dashboard_video_registration_path: (*untyped) -> String
  def edit_speaker_dashboard_video_registration_path: (*untyped) -> String
  def speaker_dashboard_video_registration_path: (*untyped) -> String
  def sponsor_dashboards_login_path: (*untyped) -> String
  def sponsor_dashboards_path: (*untyped) -> String
  def sponsor_dashboards_sponsor_profiles_path: (*untyped) -> String
  def new_sponsor_dashboards_sponsor_profile_path: (*untyped) -> String
  def edit_sponsor_dashboards_sponsor_profile_path: (*untyped) -> String
  def sponsor_dashboards_sponsor_profile_path: (*untyped) -> String
  def sponsor_dashboards_speakers_path: (*untyped) -> String
  def new_sponsor_dashboards_speaker_path: (*untyped) -> String
  def edit_sponsor_dashboards_speaker_path: (*untyped) -> String
  def sponsor_dashboards_speaker_path: (*untyped) -> String
  def talks_path: (*untyped) -> String
  def talk_path: (*untyped) -> String
  def timetables_path: (*untyped) -> String
  def dashboard_path: (*untyped) -> String
  def tracks_blank_path: (*untyped) -> String
  def kontest_path: (*untyped) -> String
  def discussion_path: (*untyped) -> String
  def hands_on_path: (*untyped) -> String
  def job_board_path: (*untyped) -> String
  def o11y_path: (*untyped) -> String
  def tracks_path: (*untyped) -> String
  def track_path: (*untyped) -> String
  def registration_path: (*untyped) -> String
  def privacy_path: (*untyped) -> String
  def coc_path: (*untyped) -> String
  def booths_path: (*untyped) -> String
  def booth_path: (*untyped) -> String
  def attachment_path: (*untyped) -> String
  def profiles_path: (*untyped) -> String
  def new_profile_path: (*untyped) -> String
  def edit_profile_path: (*untyped) -> String
  def profile_path: (*untyped) -> String
  def profiles_talks_path: (*untyped) -> String
  def profiles_new_path: (*untyped) -> String
  def profiles_edit_path: (*untyped) -> String
  def links_path: (*untyped) -> String
  def rails_postmark_inbound_emails_path: (*untyped) -> String
  def rails_relay_inbound_emails_path: (*untyped) -> String
  def rails_sendgrid_inbound_emails_path: (*untyped) -> String
  def rails_mandrill_inbound_health_check_path: (*untyped) -> String
  def rails_mandrill_inbound_emails_path: (*untyped) -> String
  def rails_mailgun_inbound_emails_path: (*untyped) -> String
  def rails_conductor_inbound_emails_path: (*untyped) -> String
  def new_rails_conductor_inbound_email_path: (*untyped) -> String
  def edit_rails_conductor_inbound_email_path: (*untyped) -> String
  def rails_conductor_inbound_email_path: (*untyped) -> String
  def new_rails_conductor_inbound_email_source_path: (*untyped) -> String
  def rails_conductor_inbound_email_sources_path: (*untyped) -> String
  def rails_conductor_inbound_email_reroute_path: (*untyped) -> String
  def rails_conductor_inbound_email_incinerate_path: (*untyped) -> String
  def rails_service_blob_path: (*untyped) -> String
  def rails_service_blob_proxy_path: (*untyped) -> String
  def rails_blob_representation_path: (*untyped) -> String
  def rails_blob_representation_proxy_path: (*untyped) -> String
  def rails_disk_service_path: (*untyped) -> String
  def update_rails_disk_service_path: (*untyped) -> String
  def rails_direct_uploads_path: (*untyped) -> String
  def rails_representation_path: (*untyped) -> String
  def rails_blob_path: (*untyped) -> String
  def rails_storage_proxy_path: (*untyped) -> String
  def rails_storage_redirect_path: (*untyped) -> String
  def rails_mailers_url: (*untyped) -> String
  def rails_info_properties_url: (*untyped) -> String
  def rails_info_routes_url: (*untyped) -> String
  def rails_info_url: (*untyped) -> String
  def root_url: (*untyped) -> String
  def auth_auth0_callback_url: (*untyped) -> String
  def auth_failure_url: (*untyped) -> String
  def logout_url: (*untyped) -> String
  def api_v1_url: (*untyped) -> String
  def api_v1_conference_url: (*untyped) -> String
  def api_v1_talks_url: (*untyped) -> String
  def api_v1_talk_url: (*untyped) -> String
  def api_v1_tracks_url: (*untyped) -> String
  def api_v1_track_url: (*untyped) -> String
  def api_v1_sponsors_url: (*untyped) -> String
  def api_v1_speakers_url: (*untyped) -> String
  def api_v1_speaker_url: (*untyped) -> String
  def api_v1_chat_messages_url: (*untyped) -> String
  def api_v1_chat_message_url: (*untyped) -> String
  def api_v1_booth_url: (*untyped) -> String
  def auth_auth0_url: (*untyped) -> String
  def admin_url: (*untyped) -> String
  def admin_debug_url: (*untyped) -> String
  def admin_chat_url: (*untyped) -> String
  def admin_accesslog_url: (*untyped) -> String
  def admin_users_url: (*untyped) -> String
  def admin_statistics_url: (*untyped) -> String
  def admin_export_statistics_url: (*untyped) -> String
  def admin_destroy_user_url: (*untyped) -> String
  def edit_admin_admin_profile_url: (*untyped) -> String
  def admin_admin_profile_url: (*untyped) -> String
  def admin_sponsors_url: (*untyped) -> String
  def edit_admin_sponsor_url: (*untyped) -> String
  def admin_sponsor_url: (*untyped) -> String
  def admin_booths_url: (*untyped) -> String
  def admin_booth_url: (*untyped) -> String
  def admin_conferences_url: (*untyped) -> String
  def edit_admin_conference_url: (*untyped) -> String
  def admin_conference_url: (*untyped) -> String
  def admin_speakers_url: (*untyped) -> String
  def edit_admin_speaker_url: (*untyped) -> String
  def admin_speaker_url: (*untyped) -> String
  def admin_export_speakers_url: (*untyped) -> String
  def admin_export_profiles_url: (*untyped) -> String
  def admin_talks_url: (*untyped) -> String
  def admin_proposals_url: (*untyped) -> String
  def admin_videos_url: (*untyped) -> String
  def admin_timetables_url: (*untyped) -> String
  def admin_timetable_url: (*untyped) -> String
  def admin_announcements_url: (*untyped) -> String
  def new_admin_announcement_url: (*untyped) -> String
  def edit_admin_announcement_url: (*untyped) -> String
  def admin_announcement_url: (*untyped) -> String
  def admin_speaker_announcements_url: (*untyped) -> String
  def new_admin_speaker_announcement_url: (*untyped) -> String
  def edit_admin_speaker_announcement_url: (*untyped) -> String
  def admin_speaker_announcement_url: (*untyped) -> String
  def admin_publish_timetable_url: (*untyped) -> String
  def admin_close_timetable_url: (*untyped) -> String
  def admin_preview_timetable_url: (*untyped) -> String
  def admin_start_on_air_url: (*untyped) -> String
  def admin_stop_on_air_url: (*untyped) -> String
  def admin_start_recording_url: (*untyped) -> String
  def admin_stop_recording_url: (*untyped) -> String
  def admin_tracks_url: (*untyped) -> String
  def admin_update_offset_url: (*untyped) -> String
  def admin_attachment_url: (*untyped) -> String
  def admin_team_url: (*untyped) -> String
  def admin_live_stream_ivs_url: (*untyped) -> String
  def admin_bulk_create_ivs_url: (*untyped) -> String
  def admin_bulk_delete_ivs_url: (*untyped) -> String
  def admin_bulk_create_media_live_url: (*untyped) -> String
  def admin_bulk_delete_media_live_url: (*untyped) -> String
  def admin_bulk_create_media_package_url: (*untyped) -> String
  def admin_bulk_delete_media_package_url: (*untyped) -> String
  def admin_harvest_jobs_url: (*untyped) -> String
  def new_admin_harvest_job_url: (*untyped) -> String
  def edit_admin_harvest_job_url: (*untyped) -> String
  def admin_harvest_job_url: (*untyped) -> String
  def team_url: (*untyped) -> String
  def speakers_entry_url: (*untyped) -> String
  def speakers_guidance_url: (*untyped) -> String
  def speakers_url: (*untyped) -> String
  def speaker_url: (*untyped) -> String
  def speaker_dashboard_url: (*untyped) -> String
  def speaker_dashboard_speakers_url: (*untyped) -> String
  def new_speaker_dashboard_speaker_url: (*untyped) -> String
  def edit_speaker_dashboard_speaker_url: (*untyped) -> String
  def speaker_dashboard_speaker_url: (*untyped) -> String
  def speaker_dashboard_video_registrations_url: (*untyped) -> String
  def new_speaker_dashboard_video_registration_url: (*untyped) -> String
  def edit_speaker_dashboard_video_registration_url: (*untyped) -> String
  def speaker_dashboard_video_registration_url: (*untyped) -> String
  def sponsor_dashboards_login_url: (*untyped) -> String
  def sponsor_dashboards_url: (*untyped) -> String
  def sponsor_dashboards_sponsor_profiles_url: (*untyped) -> String
  def new_sponsor_dashboards_sponsor_profile_url: (*untyped) -> String
  def edit_sponsor_dashboards_sponsor_profile_url: (*untyped) -> String
  def sponsor_dashboards_sponsor_profile_url: (*untyped) -> String
  def sponsor_dashboards_speakers_url: (*untyped) -> String
  def new_sponsor_dashboards_speaker_url: (*untyped) -> String
  def edit_sponsor_dashboards_speaker_url: (*untyped) -> String
  def sponsor_dashboards_speaker_url: (*untyped) -> String
  def talks_url: (*untyped) -> String
  def talk_url: (*untyped) -> String
  def timetables_url: (*untyped) -> String
  def dashboard_url: (*untyped) -> String
  def tracks_blank_url: (*untyped) -> String
  def kontest_url: (*untyped) -> String
  def discussion_url: (*untyped) -> String
  def hands_on_url: (*untyped) -> String
  def job_board_url: (*untyped) -> String
  def o11y_url: (*untyped) -> String
  def tracks_url: (*untyped) -> String
  def track_url: (*untyped) -> String
  def registration_url: (*untyped) -> String
  def privacy_url: (*untyped) -> String
  def coc_url: (*untyped) -> String
  def booths_url: (*untyped) -> String
  def booth_url: (*untyped) -> String
  def attachment_url: (*untyped) -> String
  def profiles_url: (*untyped) -> String
  def new_profile_url: (*untyped) -> String
  def edit_profile_url: (*untyped) -> String
  def profile_url: (*untyped) -> String
  def profiles_talks_url: (*untyped) -> String
  def profiles_new_url: (*untyped) -> String
  def profiles_edit_url: (*untyped) -> String
  def links_url: (*untyped) -> String
  def rails_postmark_inbound_emails_url: (*untyped) -> String
  def rails_relay_inbound_emails_url: (*untyped) -> String
  def rails_sendgrid_inbound_emails_url: (*untyped) -> String
  def rails_mandrill_inbound_health_check_url: (*untyped) -> String
  def rails_mandrill_inbound_emails_url: (*untyped) -> String
  def rails_mailgun_inbound_emails_url: (*untyped) -> String
  def rails_conductor_inbound_emails_url: (*untyped) -> String
  def new_rails_conductor_inbound_email_url: (*untyped) -> String
  def edit_rails_conductor_inbound_email_url: (*untyped) -> String
  def rails_conductor_inbound_email_url: (*untyped) -> String
  def new_rails_conductor_inbound_email_source_url: (*untyped) -> String
  def rails_conductor_inbound_email_sources_url: (*untyped) -> String
  def rails_conductor_inbound_email_reroute_url: (*untyped) -> String
  def rails_conductor_inbound_email_incinerate_url: (*untyped) -> String
  def rails_service_blob_url: (*untyped) -> String
  def rails_service_blob_proxy_url: (*untyped) -> String
  def rails_blob_representation_url: (*untyped) -> String
  def rails_blob_representation_proxy_url: (*untyped) -> String
  def rails_disk_service_url: (*untyped) -> String
  def update_rails_disk_service_url: (*untyped) -> String
  def rails_direct_uploads_url: (*untyped) -> String
  def rails_representation_url: (*untyped) -> String
  def rails_blob_url: (*untyped) -> String
  def rails_storage_proxy_url: (*untyped) -> String
  def rails_storage_redirect_url: (*untyped) -> String
end
