require 'uri'
require 'http'

# TODO: This is a temporary solution. We should use API client generated by OpenAPI Generator after CNDT2022.
class DreamkastApiClient
  def initialize(conference_abbr)
    @base_uri = ENV['DREAMKAST_API_ADDR'] || 'https://api.dev.cloudnativedays.jp'
    @conference_abbr = conference_abbr
  end

  def add_point(event_id, profile_id)
    uri = URI.join(@base_uri, "api/v1/profile/#{profile_id}/point")
    begin
      HTTP.post(uri, json: { conference: @conference_abbr, pointEventId: event_id })
    rescue => e
      p(e)
    end
  end
end
