# Configure the recorder in app_root/config/initializers/aws_xray.rb
Rails.application.config.xray = {
  # default segment name generated by XRay middleware
  name: 'dreamkast',
  patch: %I[net_http aws_sdk],
  # record db transactions as subsegments
  active_record: true,
  context_missing: 'LOG_ERROR'
}

opts = {  } # aws-xray-sdk options hash

if ENV['AWS_XRAY_DAEMON_ADDRESS']
  opts[:daemon_address] = ENV['AWS_XRAY_DAEMON_ADDRESS']
end

Rails.application.config.xray = opts