#!/usr/bin/env ruby
# frozen_string_literal: true

ENV["RAILS_ENV"] ||= "development"

require_relative "../config/environment"
require "aws/active_job/sqs/poller"

logger = ActiveSupport::Logger.new($stdout)
logger.level = Logger::INFO
logger.formatter = ::Logger::Formatter.new

Rails.logger = ActiveSupport::TaggedLogging.new(logger)
Aws::ActiveJob::SQS.configure do |config|
  config.logger = Rails.logger
end

Aws::ActiveJob::SQS::Poller.new(queues: [:fifo]).run
