class FormModels::Occupation < ActiveHash::Base
  self.data = [
    { id: 1, name: '選択してください'},
    { id: 2, name: '～経営・管理職～'},
    { id: 3, name: '経営全般'},
    { id: 4, name: '経営企画/新規事業開発'},
    { id: 5, name: '管理職'},
    { id: 6, name: '～IT関連職種～'},
    { id: 7, name: 'CIO/情報システム部門責任者'},
    { id: 8, name: '情報システム企画/設計/開発'},
    { id: 9, name: '情報システム運用管理'},
    { id: 10, name: 'IT関連プロジェクトマネージャー'},
    { id: 11, name: 'システム技術者'},
    { id: 12, name: 'コンピュータ/ハード技術者'},
    { id: 13, name: 'ソフトウェア技術者'},
    { id: 14, name: 'ネットワーク技術者'},
    { id: 15, name: 'アプリ開発'},
    { id: 16, name: 'プログラミング/コーディング'},
    { id: 17, name: 'IT関連保守/運用業務'},
    { id: 18, name: 'Webサイト管理'},
    { id: 19, name: 'その他/情報システム関連'},
    { id: 20, name: '～製造・開発・技術職関連～'},
    { id: 21, name: '研究開発'},
    { id: 22, name: '～広報・マーケティング関連～'},
    { id: 23, name: '広報/宣伝'},
    { id: 24, name: 'マーケティング/調査'},
    { id: 25, name: 'Web戦略/企画担当'},
    { id: 26, name: '～営業・販売サービス関連～'},
    { id: 27, name: '営業'},
    { id: 28, name: '～その他職種～'},
    { id: 29, name: 'デザイン/クリエイティブ系'},
    { id: 30, name: 'コンサルタント'},
    { id: 31, name: 'フリーランス'},
    { id: 32, name: '学生'},
    { id: 33, name: '無職'},
    { id: 34, name: '該当なし'},
  ]
end
