name: add labels based on .github/labeler.yml

on: pull_request

jobs:
  labeler:
    if: ${{ ! startsWith(github.head_ref, 'renovate/') }}
    uses: cloudnativedaysjp/reusable-workflows/.github/workflows/wc-add-labels.yml@main
    permissions: {}
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
