name: build container image when tags are pushed

on:
  push:
    tags: ["*"]

jobs:
  build:
    uses: cloudnativedaysjp/reusable-workflows/.github/workflows/build-image.yml@main
    permissions:
      contents: read
    with:
      image_name: dreamkast-ecs
      platforms: amd64
      aws_region: ap-northeast-1
      run-trivy: false
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
