name: build container image when branches are pushed

on:
  push:
    branches: ["**"]

jobs:
  build:
    if: github.event.pusher.name != 'dreamkast-cloudnativedays'
    uses: cloudnativedaysjp/reusable-workflows/.github/workflows/wc-build-image.yml@4129ce525f77d630ba63e86ed58c1d83bb37f7c3
    permissions:
      contents: read
      id-token: write
    with:
      image_name: dreamkast-ecs
      aws_region: us-west-2
      run-trivy: true
