name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Run database
      shell: bash
      run: |
        docker-compose up -d
    - name: Cache bundle directory
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Set up Ruby 2.7.1
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.1
    - name: Run tests
      shell: bash
      run: |
        bundle install
        bundle exec rails db:environment:set RAILS_ENV=test
        bundle exec rspec
