name: CI in the master branch

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      shell: bash
      run: |
        docker-compose -f docker-compose.yaml -f test-docker-compose.yaml up --exit-code-from app
