name: GC

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  push:
    runs-on: ubuntu-latest
    if: >-
      ! contains(github.event.pull_request.labels.*.name, 'release/major') &&
      ! contains(github.event.pull_request.labels.*.name, 'release/minor') &&
      ! contains(github.event.pull_request.labels.*.name, 'release/patch')
    steps:
      - uses: actions/checkout@v2

      - name: Checkout dreamkast-infra
        uses: actions/checkout@v2
        with:
          repository: cloudnativedaysjp/dreamkast-infra
          path: dreamkast-infra
          token:  ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.6.1"

      - name: Clean up manifests
        run: |
          BRANCH=dk-$(cat $GITHUB_EVENT_PATH | jq -r ".number")

          rm -f dreamkast-infra/manifests/app/argocd-apps/development/dreamkast-$BRANCH.yaml
          rm -rf dreamkast-infra/manifests/app/dreamkast/overlays/development/$BRANCH

      - name: Commit files
        run: |
          cd dreamkast-infra/
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add -A
          git commit -am "Clean up review apps $(echo ${{ github.head_ref }} | sed s/_/-/) (${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/issues/$(cat $GITHUB_EVENT_PATH | jq -r '.number')"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: cloudnativedaysjp/dreamkast-infra
          directory: dreamkast-infra
          branch: gc/dk-${{ github.event.pull_request.number }}

      - name: Create and Merge Pull Request
        uses: "actions/github-script@v2"
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const pr = await github.pulls.create({
              owner: "cloudnativedaysjp",
              repo: "dreamkast-infra",
              title: "Automated PR (gc/dk-${{ github.event.pull_request.number }})",
              body: "**this PR is automatically created & merged**",
              head: "gc/dk-${{ github.event.pull_request.number }}",
              base: "main"
            });
            await github.pulls.merge({
              owner: "cloudnativedaysjp",
              repo: "dreamkast-infra",
              pull_number: pr.data.number,
              merge_method: "merge",
            });
