name: GitOps for development

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  gitops:
    runs-on: ubuntu-latest
    if: ${{ ! contains(github.event.pull_request.title, '[dreamkast-releasebot]') }}
    steps:
      - uses: actions/checkout@v2

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1.0.2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: ecr
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: dreamkast-ecs
          DOCKER_BUILDKIT: 1
        run: |
          echo REF ${{ github.ref }}
          echo HEAD REF ${{ github.head_ref }}
          echo SHA ${{ github.sha }}
          IMAGE_TAG=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && IMAGE_TAG=$(echo $IMAGE_TAG | sed -e 's/^v//')

          if [ ! -e ${{ github.head_ref }} ]; then
            IMAGE_TAG=${{ github.head_ref }}
          fi

          CACHE_NODE=$ECR_REGISTRY/$ECR_REPOSITORY:node-cache
          CACHE_FETCH_LIB=$ECR_REGISTRY/$ECR_REPOSITORY:fetch-lib-cache
          CACHE_COMPILE_CACHE=$ECR_REGISTRY/$ECR_REPOSITORY:asset-compile-cache

          IMAGE_WITH_TAG=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          IMAGE_WITH_SHA=$ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}

          docker build \
            --cache-from=$CACHE_NODE \
            --cache-from=$CACHE_FETCH_LIB \
            --cache-from=$CACHE_COMPILE_CACHE \
            --build-arg=BUILDKIT_INLINE_CACHE=1 \
            -t $IMAGE_WITH_TAG \
            -t $IMAGE_WITH_SHA .

          docker build --target node -t $CACHE_NODE --build-arg=BUILDKIT_INLINE_CACHE=1  .
          docker build --target fetch-lib -t $CACHE_FETCH_LIB --build-arg=BUILDKIT_INLINE_CACHE=1  .
          docker build --target asset-compile -t $CACHE_COMPILE_CACHE --build-arg=BUILDKIT_INLINE_CACHE=1  .

          docker tag $IMAGE_WITH_TAG $IMAGE_WITH_SHA
          docker push $IMAGE_WITH_SHA
          docker push $CACHE_NODE
          docker push $CACHE_FETCH_LIB
          docker push $CACHE_COMPILE_CACHE

          echo "::set-output name=IMAGE_TAG::${IMAGE_TAG}"
          echo "::set-output name=IMAGE_WITH_TAG::${IMAGE_WITH_TAG}"
          echo "::set-output name=IMAGE_WITH_SHA::${IMAGE_WITH_SHA}"

      - name: Checkout dreamkast-infra
        uses: actions/checkout@v2
        with:
          repository: cloudnativedaysjp/dreamkast-infra
          path: dreamkast-infra
          token:  ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Get target branch from IMAGE_TAG
        id: target-branch
        env:
          IMAGE_TAG: ${{ steps.ecr.outputs.IMAGE_TAG }}
        run: |
          if  [ ! -e ${{ github.head_ref }}  ]; then
            BRANCH=dk-$(cat $GITHUB_EVENT_PATH | jq -r ".number")
          else
            BRANCH=$(echo $IMAGE_TAG | sed s/_/-/)
          fi
          echo "::set-output name=BRANCH::${BRANCH}"

      - name: Update Kubernetes resources
        uses: cloudnativedaysjp/action-dreamkast-gitops@main
        with:
          base_dir: dreamkast-infra
          app_template_dir: manifests/app/dreamkast/overlays/template
          app_target_dir: manifests/app/dreamkast/overlays/development/${{ steps.target-branch.outputs.BRANCH }}
          argo_template_file: manifests/app/argocd-apps/template/dreamkast.yaml
          argo_target_file: manifests/app/argocd-apps/development/dreamkast-${{ steps.target-branch.outputs.BRANCH }}.yaml
          image: ${{ steps.ecr.outputs.IMAGE_WITH_SHA }}
          namespace: dreamkast-${{ steps.target-branch.outputs.BRANCH }}
          replacements: BRANCH=${{ steps.target-branch.outputs.BRANCH }},ENVIRONMENT=development

      - name: Commit files
        run: |
          cd dreamkast-infra/
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add -A
          git commit -am "Bump docker tag (${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA})"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
          repository: cloudnativedaysjp/dreamkast-infra
          directory: dreamkast-infra
          branch: development/dk-${{ github.event.pull_request.number }}

      - name: Create and Merge Pull Request
        uses: "actions/github-script@v2"
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
          script: |
            const pr = await github.pulls.create({
              owner: "cloudnativedaysjp",
              repo: "dreamkast-infra",
              title: "Automated PR (development/dk-${{ github.event.pull_request.number }})",
              body: "**this PR is automatically created & merged**",
              head: "development/dk-${{ github.event.pull_request.number }}",
              base: "main"
            });
            await github.pulls.merge({
              owner: "cloudnativedaysjp",
              repo: "dreamkast-infra",
              pull_number: pr.data.number,
              merge_method: "merge",
            });

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        if: ${{ github.event.action == 'opened' }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Review app
            http://dreamkast-dk-${{ github.event.pull_request.number }}.dev.cloudnativedays.jp/
