name: GitOps for staging

on:
  push:
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/gitops-stg.yml'
      - '**.md'
    branches:
    - main

jobs:
  gitops:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1.0.2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/dreamkast-ecs
          tags: |
            type=sha,prefix=,format=long

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


      - name: Checkout dreamkast-infra
        uses: actions/checkout@v2
        with:
          repository: cloudnativedaysjp/dreamkast-infra
          path: dreamkast-infra
          token: ${{ steps.generate_token.outputs.token }}

      - name: Update Kubernetes resources
        uses: cloudnativedaysjp/action-dreamkast-gitops@main
        with:
          base_dir: dreamkast-infra
          app_template_dir: manifests/app/dreamkast/overlays/template
          app_target_dir: manifests/app/dreamkast/overlays/staging/main
          argo_template_file: manifests/app/argocd-apps/template/dreamkast.yaml
          argo_target_file: manifests/app/argocd-apps/development/dreamkast-staging.yaml
          image: ${{ steps.ecr.outputs.IMAGE_WITH_SHA }}
          namespace: dreamkast-staging
          replacements: BRANCH=main,ENVIRONMENT=staging

      - name: Commit files
        run: |
          cd dreamkast-infra/
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add -A
          git commit -am "Bump docker tag (${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA})"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
          repository: cloudnativedaysjp/dreamkast-infra
          directory: dreamkast-infra
          branch: staging/dk-main

      - name: Create and Merge Pull Request
        uses: "actions/github-script@v2"
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            const pr = await github.pulls.create({
              owner: "cloudnativedaysjp",
              repo: "dreamkast-infra",
              title: "Automated PR (staging/dk-main)",
              body: "**this PR is automatically created & merged**",
              head: "staging/dk-main",
              base: "main"
            });
            await github.pulls.merge({
              owner: "cloudnativedaysjp",
              repo: "dreamkast-infra",
              pull_number: pr.data.number,
              merge_method: "merge",
            });
