name: GitOps for staging

on:
  push:
    branches:
    - main

jobs:
  gitops-ecs:
    uses: cloudnativedaysjp/reusable-workflows/.github/workflows/rw-update-ecs-manifest.yml@main
    permissions: {}
    with:
      target-image: dreamkast_ecs
      environment: stg
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

