name: GitOps for development

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  gitops:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: ecr
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: dreamkast-ecs
          DOCKER_BUILDKIT: 1
        run: |
          echo REF ${{ github.ref }}
          echo HEAD REF ${{ github.head_ref }}
          echo SHA ${{ github.sha }}
          IMAGE_TAG=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && IMAGE_TAG=$(echo $IMAGE_TAG | sed -e 's/^v//')

          if [ ! -e ${{ github.head_ref }} ]; then
            IMAGE_TAG=${{ github.head_ref }}
          fi

          CACHE_NODE=$ECR_REGISTRY/$ECR_REPOSITORY:node-cache
          CACHE_FETCH_LIB=$ECR_REGISTRY/$ECR_REPOSITORY:fetch-lib-cache
          CACHE_COMPILE_CACHE=$ECR_REGISTRY/$ECR_REPOSITORY:asset-compile-cache

          IMAGE_WITH_TAG=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          IMAGE_WITH_SHA=$ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}

          docker build \
            --cache-from=$CACHE_NODE \
            --cache-from=$CACHE_FETCH_LIB \
            --cache-from=$CACHE_COMPILE_CACHE \
            --build-arg=BUILDKIT_INLINE_CACHE=1 \
            -t $IMAGE_WITH_TAG \
            -t $IMAGE_WITH_SHA .

          docker build --target node -t $CACHE_NODE --build-arg=BUILDKIT_INLINE_CACHE=1  .
          docker build --target fetch-lib -t $CACHE_FETCH_LIB --build-arg=BUILDKIT_INLINE_CACHE=1  .
          docker build --target asset-compile -t $CACHE_COMPILE_CACHE --build-arg=BUILDKIT_INLINE_CACHE=1  .

          docker tag $IMAGE_WITH_TAG $IMAGE_WITH_SHA
          docker push $IMAGE_WITH_SHA
          docker push $CACHE_NODE
          docker push $CACHE_FETCH_LIB
          docker push $CACHE_COMPILE_CACHE

          echo "::set-output name=IMAGE_TAG::${IMAGE_TAG}"
          echo "::set-output name=IMAGE_WITH_TAG::${IMAGE_WITH_TAG}"
          echo "::set-output name=IMAGE_WITH_SHA::${IMAGE_WITH_SHA}"

      - name: Checkout dreamkast-infra
        uses: actions/checkout@v2
        with:
          repository: cloudnativedaysjp/dreamkast-infra
          path: dreamkast-infra
          token:  ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.6.1"

      - name: Get target branch from IMAGE_TAG
        id: target-branch
        env:
          IMAGE_TAG: ${{ steps.ecr.outputs.IMAGE_TAG }}
        run: |
          if  [ ! -e ${{ github.head_ref }}  ]; then
            BRANCH=dk-$(cat $GITHUB_EVENT_PATH | jq -r ".number")
          else
            BRANCH=$(echo $IMAGE_TAG | sed s/_/-/)
          fi
          echo "::set-output name=BRANCH::${BRANCH}"

      - name: Update Kubernetes resources
        env:
          BASE_DIR: dreamkast-infra
          APP_TEMPLATE_DIR: manifests/app/dreamkast/overlays/template
          APP_TARGET_DIR: manifests/app/dreamkast/overlays/development/${{ steps.target-branch.outputs.BRANCH }}
          ARGO_TEMPLATE_FILE: manifests/app/argocd-apps/template/dreamkast.yaml
          ARGO_TARGET_FILE: manifests/app/argocd-apps/development/dreamkast-${{ steps.target-branch.outputs.BRANCH }}.yaml
          IMAGE: ${{ steps.ecr.outputs.IMAGE_WITH_SHA }}
          NAMESPACE: dreamkast-${{ steps.target-branch.outputs.BRANCH }}
          REPLACEMENTS: BRANCH=${{ steps.target-branch.outputs.BRANCH }}
        run: |
          echo "========Update application manifests=========="
          (
          if [ ! -d ${BASE_DIR}/${APP_TARGET_DIR} ]; then
            cp -r ${BASE_DIR}/${APP_TEMPLATE_DIR} ${BASE_DIR}/${APP_TARGET_DIR}
          fi
          cd ${BASE_DIR}/${APP_TARGET_DIR}
          kustomize edit set image ${IMAGE}
          kustomize edit set namespace ${NAMESPACE}
          IFS=, ARR=(${REPLACEMENTS})
          for r in "${ARR[@]}"; do
            before=$(echo $r | cut -d= -f1)
            after=$(echo $r | cut -d= -f2)
            sed -i -e s/$before/$after/g ./*
          done
          # output
          cat kustomization.yaml
          )

          echo "========Generate ArgoCD app=========="
          (
          if [ ! -d ${BASE_DIR}/${ARGO_TARGET_FILE} ]; then
            cp ${BASE_DIR}/${ARGO_TEMPLATE_FILE} ${BASE_DIR}/${ARGO_TARGET_FILE}
          fi
          sed -i -e s/NAMESPACE/${NAMESPACE}/ ${BASE_DIR}/${ARGO_TARGET_FILE}
          IFS=, ARR=(${REPLACEMENTS})
          for r in "${ARR[@]}"; do
            before=$(echo $r | cut -d= -f1)
            after=$(echo $r | cut -d= -f2)
            sed -i -e s/$before/$after/g ${BASE_DIR}/${ARGO_TARGET_FILE}
          done
          )

      - name: Commit files
        run: |
          cd dreamkast-infra/
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add -A
          git commit -am "Bump docker tag (${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA})"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: cloudnativedaysjp/dreamkast-infra
          directory: dreamkast-infra
          branch: main

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        if: ${{ github.event.action == 'opened' }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Review app
            http://dreamkast-dk-${{ github.event.pull_request.number }}.dev.cloudnativedays.jp/
