name: GitOps for production

on:
  push:
    tags:
      - v*

jobs:
  gitops:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Checkout dreamkast-infra
        uses: actions/checkout@v4
        with:
          repository: cloudnativedaysjp/dreamkast-infra
          path: dreamkast-infra
          token: ${{ steps.generate_token.outputs.token }}

      - name: Update Kubernetes manifest
        working-directory: dreamkast-infra/manifests/app/dreamkast/overlays/production/main
        run: |
          kustomize edit set image dreamkast-ecs=${{ steps.login-ecr.outputs.registry }}/dreamkast-ecs:${{ github.sha }}

      - name: Commit files
        working-directory: dreamkast-infra/
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add -A
          git commit -am "Bump docker tag (${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA})"

      - name: Set current unixtime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "UNIXTIME=$(date +'+%s')" >> $GITHUB_ENV

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
          repository: cloudnativedaysjp/dreamkast-infra
          directory: dreamkast-infra
          branch: gitops/production/dk-main_${{ env.UNIXTIME }}

      - name: Create and Merge Pull Request
        uses: "actions/github-script@v7"
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            const pr = await github.rest.pulls.create({
              owner: "cloudnativedaysjp",
              repo: "dreamkast-infra",
              title: "Automated PR (gitops/production/dk-main)",
              body: "**this PR is automatically created & merged**",
              head: "gitops/production/dk-main_${{ env.UNIXTIME }}",
              base: "main"
            });
            await github.rest.pulls.merge({
              owner: "cloudnativedaysjp",
              repo: "dreamkast-infra",
              pull_number: pr.data.number,
              merge_method: "squash",
            });

      - name: Sentry Release
        uses: getsentry/action-release@v1.7.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_URL: https://sentry.cloudnativedays.jp
        with:
          environment: production
          version: ${{ github.sha }} # same as image tag


  gitops-ecs:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5

      - name: Install jsonnet
        run: |
          go install github.com/google/go-jsonnet/cmd/jsonnet@latest
          go install github.com/google/go-jsonnet/cmd/jsonnetfmt@latest

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout dreamkast-infra
        uses: actions/checkout@v4
        with:
          repository: cloudnativedaysjp/dreamkast-infra
          path: dreamkast-infra
          token: ${{ steps.generate_token.outputs.token }}

      - name: get tag name
        id: get-tag-name
        run: echo "tag-name=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Update image-tags
        working-directory: dreamkast-infra/ecspresso/prod
        run: |
          cat << _EOL_ | jsonnet - > ./const.libsonnet.tmp
          local const = import './const.libsonnet';

          const + {
            imageTags: const.imageTags + {
              dreamkast_ecs: "${{ steps.get-tag-name.outputs.tag-name }}",
            },
          }
          _EOL_
          mv const.libsonnet.tmp const.libsonnet
          jsonnetfmt -i const.libsonnet

      - name: Commit files
        id: commit_files
        continue-on-error: true
        working-directory: dreamkast-infra/
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add -A
          git commit -am "Bump docker tag (${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/releases/tag/${{ steps.get-tag-name.outputs.tag-name }})"

      - name: Push changes
        if: steps.commit_files.outcome == 'success'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
          repository: cloudnativedaysjp/dreamkast-infra
          directory: dreamkast-infra
          branch: gitops/production/dk-main

      - name: Create and Merge Pull Request
        if: steps.commit_files.outcome == 'success'
        uses: "actions/github-script@v7"
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            const pr = await github.rest.pulls.create({
              owner: "cloudnativedaysjp",
              repo: "dreamkast-infra",
              title: "Automated PR (gitops/production/dk-main)",
              body: "**this PR is automatically created & merged**",
              head: "gitops/production/dk-main",
              base: "main"
            });
            await github.rest.pulls.merge({
              owner: "cloudnativedaysjp",
              repo: "dreamkast-infra",
              pull_number: pr.data.number,
              merge_method: "squash",
            });
