name: GitOps for production

on:
  push:
    tags:
      - v*

jobs:
  gitops-ecs:
    uses: cloudnativedaysjp/reusable-workflows/.github/workflows/wc-update-ecs-manifest.yml@main
    permissions:
      id-token: write
    with:
      target-image: dreamkast_ecs
      environment: prod
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

