name: GitOps for staging

on:
  push:
    branches:
    - main

jobs:
  gitops-ecs:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5

      - name: Install jsonnet
        run: |
          go install github.com/google/go-jsonnet/cmd/jsonnet@latest
          go install github.com/google/go-jsonnet/cmd/jsonnetfmt@latest

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout dreamkast-infra
        uses: actions/checkout@v4
        with:
          repository: cloudnativedaysjp/dreamkast-infra
          path: dreamkast-infra
          token: ${{ steps.generate_token.outputs.token }}

      - name: Update image-tags
        working-directory: dreamkast-infra/ecspresso/stg
        run: |
          cat << _EOL_ | jsonnet - > ./const.libsonnet.tmp
          local const = import './const.libsonnet';

          const + {
            imageTags: const.imageTags + {
              dreamkast_ecs: "${{ github.sha }}",
            },
          }
          _EOL_
          mv const.libsonnet.tmp const.libsonnet
          jsonnetfmt -i const.libsonnet

      - name: Commit files
        id: commit_files
        continue-on-error: true
        working-directory: dreamkast-infra/
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add -A
          git commit -am "Bump docker tag (${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA})"

      - name: Push changes
        if: steps.commit_files.outcome == 'success'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
          repository: cloudnativedaysjp/dreamkast-infra
          directory: dreamkast-infra
          branch: gitops/staging/dk-main

      - name: Create and Merge Pull Request
        if: steps.commit_files.outcome == 'success'
        uses: "actions/github-script@v7"
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            const pr = await github.rest.pulls.create({
              owner: "cloudnativedaysjp",
              repo: "dreamkast-infra",
              title: "Automated PR (gitops/staging/dk-main)",
              body: "**this PR is automatically created & merged**",
              head: "gitops/staging/dk-main",
              base: "main"
            });
            await github.rest.pulls.merge({
              owner: "cloudnativedaysjp",
              repo: "dreamkast-infra",
              pull_number: pr.data.number,
              merge_method: "squash",
            });
