name: add 'reviewapps/ignore' label to PR when all updated files match to paths_ignore

on: pull_request

jobs:
  labeling:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.7
        with:
          use_fork_point: true

      - name: List all changed files
        id: check-paths-ignore
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          FLAG=$(cat << '_EOF_' | python
          import os
          import sys
          import pathlib
          paths_ignore = [
            '.github/**/*.yml',
            '**.md',
          ]
          all_changed_files = os.getenv("ALL_CHANGED_FILES").split()
          for filename in all_changed_files:
            if not any(list(map(lambda pattern: pathlib.PurePath(filename).match(pattern), paths_ignore))):
              sys.exit()
          print("true")
          _EOF_
          )
          echo "::set-output name=FLAG::${FLAG}"

      - name: Labeling 'reviewapps/ignore' to PR
        if: ${{ steps.check-paths-ignore.outputs.FLAG == 'true' }}
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['reviewapps/ignore']
            });
