name: Push a new tag when Pull Requests are merged

on:
  pull_request:
    types: [closed]

jobs:
  tagging:
    if: ${{ contains(github.event.pull_request.title, '[dreamkast-releasebot]') }}
    uses: cloudnativedaysjp/reusable-workflows/.github/workflows/wc-push-new-tag.yml@main
    permissions:
      pull-requests: write
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
