name: Release new version based on .github/release.yml

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    uses: cloudnativedaysjp/reusable-workflows/.github/workflows/wc-release-new-version.yml@4129ce525f77d630ba63e86ed58c1d83bb37f7c3
    permissions:
      contents: write
