name: deploy reviewapp

on:
  push:
    branches-ignore:
    - main
  pull_request:
    types:
      - labeled

jobs:
  reviewapp:
    if: ${{ ! startsWith(github.head_ref, 'renovate/') }}
    uses: cloudnativedaysjp/reusable-workflows/.github/workflows/wc-update-ecs-reviewapp.yml@main
    permissions:
      contents: read
      pull-requests: read
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  update-comment:
    needs: [reviewapp]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: marocchino/sticky-pull-request-comment@52423e01640425a022ef5fd42c6fb5f633a02728 # v2.9.1
        if: needs.reviewapp.outputs.outcome == 'success'
        with:
          number: ${{ needs.reviewapp.outputs.pr_number }}
          header: reviewapp
          recreate: true
          message: |
            Review app
            * https://dreamkast-dk-${{ needs.reviewapp.outputs.pr_number }}.dev.cloudnativedays.jp
      - uses: marocchino/sticky-pull-request-comment@52423e01640425a022ef5fd42c6fb5f633a02728 # v2.9.1
        if: needs.reviewapp.outputs.outcome != 'success'
        with:
          number: ${{ needs.reviewapp.outputs.pr_number }}
          header: reviewapp
          delete: true
