name: cleanup reviewapps

on:
  schedule:
    - cron:  '*/30 * * * *'
  workflow_dispatch:

jobs:
  cleanup:
    uses: cloudnativedaysjp/reusable-workflows/.github/workflows/wc-cleanup-ecs-reviewapps.yml@main
    permissions:
      id-token: write
    with:
      prefix: dk-
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
