name: deploy reviewapp

on:
  push:
    branches-ignore:
    - main
  pull_request:
    types:
      - labeled

jobs:
  reviewapp:
    if: ${{ ! startsWith(github.head_ref, 'renovate/') }}
    uses: cloudnativedaysjp/reusable-workflows/.github/workflows/wc-update-ecs-reviewapp.yml@main
    permissions:
      contents: read
      pull-requests: read
      id-token: write
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

  update-comment:
    needs: [reviewapp]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    timeout-minutes: 3
    steps:
      - uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2.9.4
        if: needs.reviewapp.outputs.outcome == 'success'
        with:
          number: ${{ needs.reviewapp.outputs.pr_number }}
          header: reviewapp
          recreate: true
          message: |
            Review app
            * https://dreamkast-dk-${{ needs.reviewapp.outputs.pr_number }}.dev.cloudnativedays.jp
      - uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2.9.4
        if: needs.reviewapp.outputs.outcome != 'success'
        with:
          number: ${{ needs.reviewapp.outputs.pr_number }}
          header: reviewapp
          delete: true
