name: cleanup reviewapps

on:
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  cleanup:
    uses: cloudnativedaysjp/reusable-workflows/.github/workflows/rw-cleanup-ecs-reviewapps.yml@main
    with:
      prefix: dk-
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
