name: build
on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/trivy.yml'
      - '**.md'
    branches:
      - main
    types: [opened, synchronize]
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'
